using System;
using System.Collections.Generic;
using System.Linq;
using Plugin.BLE.Abstractions.Extensions;

namespace Plugin.BLE.Abstractions
{
    /// <summary>
    /// Provides a list of known characteristics.
    /// </summary>
    public static class KnownCharacteristics
    {
        static KnownCharacteristics()
        {
            //ToDo do we need a lock here?
            LookupTable = Characteristics.ToDictionary(c => c.Id, c => c);
        }

        /// <summary>
        /// Look up a known characteristic via its Id.
        /// </summary>
        public static KnownCharacteristic Lookup(Guid id)
        {
            return LookupTable.ContainsKey(id) ? LookupTable[id] : new KnownCharacteristic("Unknown characteristic", Guid.Empty);
        }

        private static readonly Dictionary<Guid, KnownCharacteristic> LookupTable;

        /// <summary>
        /// https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicsHome.aspx
        /// </summary>
        private static readonly List<KnownCharacteristic> Characteristics =
        [
            new KnownCharacteristic("Alert Category ID",                                    GuidExtension.UuidFromPartial(0x2a43)),
            new KnownCharacteristic("Alert Category ID Bit Mask",                           GuidExtension.UuidFromPartial(0x2a42)),
            new KnownCharacteristic("Alert Level",                                          GuidExtension.UuidFromPartial(0x2a06)),
            new KnownCharacteristic("Alert Notification Control Point",                     GuidExtension.UuidFromPartial(0x2a44)),
            new KnownCharacteristic("Alert Status",                                         GuidExtension.UuidFromPartial(0x2a3f)),
            new KnownCharacteristic("Appearance",                                           GuidExtension.UuidFromPartial(0x2a01)),
            new KnownCharacteristic("Battery Level",                                        GuidExtension.UuidFromPartial(0x2a19)),
            new KnownCharacteristic("Blood Pressure Feature",                               GuidExtension.UuidFromPartial(0x2a49)),
            new KnownCharacteristic("Blood Pressure Measurement",                           GuidExtension.UuidFromPartial(0x2a35)),
            new KnownCharacteristic("Body Sensor Location",                                 GuidExtension.UuidFromPartial(0x2a38)),
            new KnownCharacteristic("Boot Keyboard Input Report",                           GuidExtension.UuidFromPartial(0x2a22)),
            new KnownCharacteristic("Boot Keyboard Output Report",                          GuidExtension.UuidFromPartial(0x2a32)),
            new KnownCharacteristic("Boot Mouse Input Report",                              GuidExtension.UuidFromPartial(0x2a33)),
            new KnownCharacteristic("CSC Feature",                                          GuidExtension.UuidFromPartial(0x2a5c)),
            new KnownCharacteristic("CSC Measurement",                                      GuidExtension.UuidFromPartial(0x2a5b)),
            new KnownCharacteristic("Current Time",                                         GuidExtension.UuidFromPartial(0x2a2b)),
            new KnownCharacteristic("Cycling Power Control Point",                          GuidExtension.UuidFromPartial(0x2a66)),
            new KnownCharacteristic("Cycling Power Feature",                                GuidExtension.UuidFromPartial(0x2a65)),
            new KnownCharacteristic("Cycling Power Measurement",                            GuidExtension.UuidFromPartial(0x2a63)),
            new KnownCharacteristic("Cycling Power Vector",                                 GuidExtension.UuidFromPartial(0x2a64)),
            new KnownCharacteristic("Date Time",                                            GuidExtension.UuidFromPartial(0x2a08)),
            new KnownCharacteristic("Day Date Time",                                        GuidExtension.UuidFromPartial(0x2a0a)),
            new KnownCharacteristic("Day of Week",                                          GuidExtension.UuidFromPartial(0x2a09)),
            new KnownCharacteristic("Device Name",                                          GuidExtension.UuidFromPartial(0x2a00)),
            new KnownCharacteristic("DST Offset",                                           GuidExtension.UuidFromPartial(0x2a0d)),
            new KnownCharacteristic("Exact Time 256",                                       GuidExtension.UuidFromPartial(0x2a0c)),
            new KnownCharacteristic("Firmware Revision String",                             GuidExtension.UuidFromPartial(0x2a26)),
            new KnownCharacteristic("Fitness Machine Control Point",                        GuidExtension.UuidFromPartial(0x2ad9)),
            new KnownCharacteristic("Fitness Machine Feature",                              GuidExtension.UuidFromPartial(0x2acc)),
            new KnownCharacteristic("Fitness Machine Status",                               GuidExtension.UuidFromPartial(0x2ada)),
            new KnownCharacteristic("Glucose Feature",                                      GuidExtension.UuidFromPartial(0x2a51)),
            new KnownCharacteristic("Glucose Measurement",                                  GuidExtension.UuidFromPartial(0x2a18)),
            new KnownCharacteristic("Glucose Measure Context",                              GuidExtension.UuidFromPartial(0x2a34)),
            new KnownCharacteristic("Hardware Revision String",                             GuidExtension.UuidFromPartial(0x2a27)),
            new KnownCharacteristic("Heart Rate Control Point",                             GuidExtension.UuidFromPartial(0x2a39)),
            new KnownCharacteristic("Heart Rate Measurement",                               GuidExtension.UuidFromPartial(0x2a37)),
            new KnownCharacteristic("HID Control Point",                                    GuidExtension.UuidFromPartial(0x2a4c)),
            new KnownCharacteristic("HID Information",                                      GuidExtension.UuidFromPartial(0x2a4a)),
            new KnownCharacteristic("IEEE 11073-20601 Regulatory Certification Data List",  GuidExtension.UuidFromPartial(0x2a2a)),
            new KnownCharacteristic("Intermediate Cuff Pressure",                           GuidExtension.UuidFromPartial(0x2a36)),
            new KnownCharacteristic("Intermediate Temperature",                             GuidExtension.UuidFromPartial(0x2a1e)),
            new KnownCharacteristic("LN Control Point",                                     GuidExtension.UuidFromPartial(0x2a6b)),
            new KnownCharacteristic("LN Feature",                                           GuidExtension.UuidFromPartial(0x2a6a)),
            new KnownCharacteristic("Local Time Information",                               GuidExtension.UuidFromPartial(0x2a0f)),
            new KnownCharacteristic("Location And Speed",                                   GuidExtension.UuidFromPartial(0x2a67)),
            new KnownCharacteristic("Manufacturer Name String",                             GuidExtension.UuidFromPartial(0x2a29)),
            new KnownCharacteristic("Measurement Interval",                                 GuidExtension.UuidFromPartial(0x2a21)),
            new KnownCharacteristic("Model Number String",                                  GuidExtension.UuidFromPartial(0x2a24)),
            new KnownCharacteristic("Navigation",                                           GuidExtension.UuidFromPartial(0x2a68)),
            new KnownCharacteristic("New Alert",                                            GuidExtension.UuidFromPartial(0x2a46)),
            new KnownCharacteristic("Peripheral Preferred Connection Parameters",           GuidExtension.UuidFromPartial(0x2a04)),
            new KnownCharacteristic("Peripheral Privacy Flag",                              GuidExtension.UuidFromPartial(0x2a02)),
            new KnownCharacteristic("PnP ID",                                               GuidExtension.UuidFromPartial(0x2a50)),
            new KnownCharacteristic("Position Quality",                                     GuidExtension.UuidFromPartial(0x2a69)),
            new KnownCharacteristic("Protocol Mode",                                        GuidExtension.UuidFromPartial(0x2a4e)),
            new KnownCharacteristic("Reconnection Address",                                 GuidExtension.UuidFromPartial(0x2a03)),
            new KnownCharacteristic("Record Access Control Point (Test Version)",           GuidExtension.UuidFromPartial(0x2a52)),
            new KnownCharacteristic("Reference Time Information",                           GuidExtension.UuidFromPartial(0x2a14)),
            new KnownCharacteristic("Report",                                               GuidExtension.UuidFromPartial(0x2a4d)),
            new KnownCharacteristic("Report Map",                                           GuidExtension.UuidFromPartial(0x2a4b)),
            new KnownCharacteristic("Ringer Control Point",                                 GuidExtension.UuidFromPartial(0x2a40)),
            new KnownCharacteristic("Ringer Setting",                                       GuidExtension.UuidFromPartial(0x2a41)),
            new KnownCharacteristic("RSC Feature",                                          GuidExtension.UuidFromPartial(0x2a54)),
            new KnownCharacteristic("RSC Measurement",                                      GuidExtension.UuidFromPartial(0x2a53)),
            new KnownCharacteristic("SC Control Point",                                     GuidExtension.UuidFromPartial(0x2a55)),
            new KnownCharacteristic("Scan Interval Window",                                 GuidExtension.UuidFromPartial(0x2a4f)),
            new KnownCharacteristic("Scan Refresh",                                         GuidExtension.UuidFromPartial(0x2a31)),
            new KnownCharacteristic("Sensor Location",                                      GuidExtension.UuidFromPartial(0x2a5d)),
            new KnownCharacteristic("Serial Number String",                                 GuidExtension.UuidFromPartial(0x2a25)),
            new KnownCharacteristic("Service Changed",                                      GuidExtension.UuidFromPartial(0x2a05)),
            new KnownCharacteristic("Software Revision String",                             GuidExtension.UuidFromPartial(0x2a28)),
            new KnownCharacteristic("Supported New Alert Category",                         GuidExtension.UuidFromPartial(0x2a47)),
            new KnownCharacteristic("Supported Speed Range",                                GuidExtension.UuidFromPartial(0x2ad4)),
            new KnownCharacteristic("Supported Unread Alert Category",                      GuidExtension.UuidFromPartial(0x2a48)),
            new KnownCharacteristic("System ID",                                            GuidExtension.UuidFromPartial(0x2a23)),
            new KnownCharacteristic("Temperature Measurement",                              GuidExtension.UuidFromPartial(0x2a1c)),
            new KnownCharacteristic("Temperature Type",                                     GuidExtension.UuidFromPartial(0x2a1d)),
            new KnownCharacteristic("Time Accuracy",                                        GuidExtension.UuidFromPartial(0x2a12)),
            new KnownCharacteristic("Time Source",                                          GuidExtension.UuidFromPartial(0x2a13)),
            new KnownCharacteristic("Time Update Control Point",                            GuidExtension.UuidFromPartial(0x2a16)),
            new KnownCharacteristic("Time Update State",                                    GuidExtension.UuidFromPartial(0x2a17)),
            new KnownCharacteristic("Time with DST",                                        GuidExtension.UuidFromPartial(0x2a11)),
            new KnownCharacteristic("Time Zone",                                            GuidExtension.UuidFromPartial(0x2a0e)),
            new KnownCharacteristic("Training Status",                                      GuidExtension.UuidFromPartial(0x2ad3)),
            new KnownCharacteristic("Treadmill Data",                                       GuidExtension.UuidFromPartial(0x2acd)),
            new KnownCharacteristic("Tx Power Level",                                       GuidExtension.UuidFromPartial(0x2a07)),
            new KnownCharacteristic("Unread Alert Status",                                  GuidExtension.UuidFromPartial(0x2a45)),

            new KnownCharacteristic("Aerobic Heart Rate Lower Limit",                   GuidExtension.UuidFromPartial(0x2a7e)),
            new KnownCharacteristic("Aerobic Heart Rate Uppoer Limit",                  GuidExtension.UuidFromPartial(0x2a84)),
            new KnownCharacteristic("Age",                                              GuidExtension.UuidFromPartial(0x2a80)),
            new KnownCharacteristic("Aggregate Input",                                  GuidExtension.UuidFromPartial(0x2a5a)),
            new KnownCharacteristic("Anaerobic Heart Rate Lower Limit",                 GuidExtension.UuidFromPartial(0x2a81)),
            new KnownCharacteristic("Anaerobic Heart Rate Upper Limit",                 GuidExtension.UuidFromPartial(0x2a82)),
            new KnownCharacteristic("Anaerobic Threshold",                              GuidExtension.UuidFromPartial(0x2a83)),
            new KnownCharacteristic("Analog Input",                                     GuidExtension.UuidFromPartial(0x2a58)),
            new KnownCharacteristic("Fat Burn Heart Rate Upper Limit",                  GuidExtension.UuidFromPartial(0x2a89)),
            new KnownCharacteristic("Apparent Wind Direction",                          GuidExtension.UuidFromPartial(0x2a73)),
            new KnownCharacteristic("Apparent Wind Speed",                              GuidExtension.UuidFromPartial(0x2a72)),
            new KnownCharacteristic("Body Composition Feature",                         GuidExtension.UuidFromPartial(0x2a9b)),
            new KnownCharacteristic("Body Composition Measurement",                     GuidExtension.UuidFromPartial(0x2a9c)),
            new KnownCharacteristic("Database Change Increment",                        GuidExtension.UuidFromPartial(0x2a99)),
            new KnownCharacteristic("Date of Birth",                                    GuidExtension.UuidFromPartial(0x2a85)),
            new KnownCharacteristic("Date of Threshold Assessment",                     GuidExtension.UuidFromPartial(0x2a86)),
            new KnownCharacteristic("Descriptor Value Changed",                         GuidExtension.UuidFromPartial(0x2a7d)),
            new KnownCharacteristic("Dew Point",                                        GuidExtension.UuidFromPartial(0x2a7b)),
            new KnownCharacteristic("Digital Input",                                    GuidExtension.UuidFromPartial(0x2a56)),
            new KnownCharacteristic("Digital Output",                                   GuidExtension.UuidFromPartial(0x2a57)),
            new KnownCharacteristic("Elevation",                                        GuidExtension.UuidFromPartial(0x2a6c)),
            new KnownCharacteristic("Email Address",                                    GuidExtension.UuidFromPartial(0x2a87)),
            new KnownCharacteristic("Exact Time 100",                                   GuidExtension.UuidFromPartial(0x2a0b)),
            new KnownCharacteristic("Fat Burn Heart Rate Lower Limit",                  GuidExtension.UuidFromPartial(0x2a88)),
            new KnownCharacteristic("First Name",                                       GuidExtension.UuidFromPartial(0x2a8a)),
            new KnownCharacteristic("Five Zone Heart Rate Limits",                      GuidExtension.UuidFromPartial(0x2a8b)),
            new KnownCharacteristic("Gender",                                           GuidExtension.UuidFromPartial(0x2a8c)),
            new KnownCharacteristic("Gust Factor",                                      GuidExtension.UuidFromPartial(0x2a74)),
            new KnownCharacteristic("Heart Rate Max",                                   GuidExtension.UuidFromPartial(0x2a8d)),
            new KnownCharacteristic("Heat Index",                                       GuidExtension.UuidFromPartial(0x2a7a)),
            new KnownCharacteristic("Height",                                           GuidExtension.UuidFromPartial(0x2a8e)),
            new KnownCharacteristic("Hip Circumference",                                GuidExtension.UuidFromPartial(0x2a8f)),
            new KnownCharacteristic("Humidity",                                         GuidExtension.UuidFromPartial(0x2a6f)),
            new KnownCharacteristic("Irradiance",                                       GuidExtension.UuidFromPartial(0x2a77)),
            new KnownCharacteristic("Last Name",                                        GuidExtension.UuidFromPartial(0x2a90)),
            new KnownCharacteristic("Maximum Recommended Heart Rate",                   GuidExtension.UuidFromPartial(0x2a91)),
            new KnownCharacteristic("Network Availability",                             GuidExtension.UuidFromPartial(0x2a3e)),
            new KnownCharacteristic("Pollen Concentration",                             GuidExtension.UuidFromPartial(0x2a75)),
            new KnownCharacteristic("Pressure",                                         GuidExtension.UuidFromPartial(0x2a6d)),
            new KnownCharacteristic("Rainfall",                                         GuidExtension.UuidFromPartial(0x2a78)),
            new KnownCharacteristic("Resting Heart Rate",                               GuidExtension.UuidFromPartial(0x2a92)),
            new KnownCharacteristic("Scientific Temperature in Celsius",                GuidExtension.UuidFromPartial(0x2a3c)),
            new KnownCharacteristic("Secondary Time Zone",                              GuidExtension.UuidFromPartial(0x2a10)),
            new KnownCharacteristic("Sport Type for Aerobic and Anaerobic Thresholds",  GuidExtension.UuidFromPartial(0x2a93)),
            new KnownCharacteristic("String",                                           GuidExtension.UuidFromPartial(0x2a3d)),
            new KnownCharacteristic("Temperature",                                      GuidExtension.UuidFromPartial(0x2a6e)),
            new KnownCharacteristic("Temperature in Celsius",                           GuidExtension.UuidFromPartial(0x2a1f)),
            new KnownCharacteristic("Temperature in Fahrenheit",                        GuidExtension.UuidFromPartial(0x2a20)),
            new KnownCharacteristic("Three Zone Heart Rate Limits",                     GuidExtension.UuidFromPartial(0x2a94)),
            new KnownCharacteristic("Time Broadcast",                                   GuidExtension.UuidFromPartial(0x2a15)),
            new KnownCharacteristic("Trend",                                            GuidExtension.UuidFromPartial(0x2a7c)),
            new KnownCharacteristic("True Wind Direction",                              GuidExtension.UuidFromPartial(0x2a71)),
            new KnownCharacteristic("True Wind Speed",                                  GuidExtension.UuidFromPartial(0x2a70)),
            new KnownCharacteristic("Two Zone Heart Rate Limit",                        GuidExtension.UuidFromPartial(0x2a95)),
            new KnownCharacteristic("User Control Point",                               GuidExtension.UuidFromPartial(0x2a9f)),
            new KnownCharacteristic("User Index",                                       GuidExtension.UuidFromPartial(0x2a9a)),
            new KnownCharacteristic("UV Index",                                         GuidExtension.UuidFromPartial(0x2a76)),
            new KnownCharacteristic("VO2 Max",                                          GuidExtension.UuidFromPartial(0x2a96)),
            new KnownCharacteristic("Waist Circumference",                              GuidExtension.UuidFromPartial(0x2a97)),
            new KnownCharacteristic("Weight",                                           GuidExtension.UuidFromPartial(0x2a98)),
            new KnownCharacteristic("Weight Measurement",                               GuidExtension.UuidFromPartial(0x2a9d)),
            new KnownCharacteristic("Weight Scale Feature",                             GuidExtension.UuidFromPartial(0x2a9e)),
            new KnownCharacteristic("Wind Chill",                                       GuidExtension.UuidFromPartial(0x2a79)),
            new KnownCharacteristic("Battery Level State",                              GuidExtension.UuidFromPartial(0x2a1b)),
            new KnownCharacteristic("Battery Power State",                              GuidExtension.UuidFromPartial(0x2a1a)),
            new KnownCharacteristic("Latitude",                                         GuidExtension.UuidFromPartial(0x2a2d)),
            new KnownCharacteristic("Longitude",                                        GuidExtension.UuidFromPartial(0x2a2e)),
            new KnownCharacteristic("Position 2D",                                      GuidExtension.UuidFromPartial(0x2a2f)),
            new KnownCharacteristic("Position 3D",                                      GuidExtension.UuidFromPartial(0x2a30)),
            new KnownCharacteristic("Pulse Oximetry Continuous Measurement",            GuidExtension.UuidFromPartial(0x2a5f)),
            new KnownCharacteristic("Pulse Oximetry Control Point",                     GuidExtension.UuidFromPartial(0x2a62)),
            new KnownCharacteristic("Pulse Oximetry Features",                          GuidExtension.UuidFromPartial(0x2a61)),
            new KnownCharacteristic("Pulse Oximetry Pulsatile Event",                   GuidExtension.UuidFromPartial(0x2a60)),
            new KnownCharacteristic("Pulse Oximetry Spot-Check Measurement",            GuidExtension.UuidFromPartial(0x2a5e)),
            new KnownCharacteristic("Removable",                                        GuidExtension.UuidFromPartial(0x2a3a)),
            new KnownCharacteristic("Service Required",                                 GuidExtension.UuidFromPartial(0x2a3b)),

            new KnownCharacteristic("TI SensorTag Keys Data",                           Guid.ParseExact("0000ffe1-0000-1000-8000-00805f9b34fb", "d")),
            new KnownCharacteristic("TI SensorTag Infrared Temperature Data",           Guid.ParseExact("f000aa01-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Infrared Temperature On/Off",         Guid.ParseExact("f000aa02-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Infrared Temperature Sample Rate",    Guid.ParseExact("f000aa03-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Accelerometer Data",                  Guid.ParseExact("f000aa11-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Accelerometer On/Off",                Guid.ParseExact("f000aa12-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Accelerometer Sample Rate",           Guid.ParseExact("f000aa13-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Humidity Data",                       Guid.ParseExact("f000aa21-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Humidity On/Off",                     Guid.ParseExact("f000aa22-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Humidity Sample Rate",                Guid.ParseExact("f000aa23-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Magnometer Data",                     Guid.ParseExact("f000aa31-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Magnometer On/Off",                   Guid.ParseExact("f000aa32-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Magnometer Sample Rate",              Guid.ParseExact("f000aa33-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Barometer Data",                      Guid.ParseExact("f000aa41-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Barometer On/Off",                    Guid.ParseExact("f000aa42-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Barometer Calibration",               Guid.ParseExact("f000aa43-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Barometer Sample Rate",               Guid.ParseExact("f000aa44-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Gyroscope Data",                      Guid.ParseExact("f000aa51-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Gyroscope On/Off",                    Guid.ParseExact("f000aa52-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Gyroscope Sample Rate",               Guid.ParseExact("f000aa53-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Test Data",                           Guid.ParseExact("f000aa61-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Test Configuration",                  Guid.ParseExact("f000aa62-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Connection Parameters",               Guid.ParseExact("f000ccc1-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Connection Request Parameters",       Guid.ParseExact("f000ccc2-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag Connection Request Disconnect",       Guid.ParseExact("f000ccc3-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag OAD Image Identify",                  Guid.ParseExact("f000ffc1-0451-4000-b000-000000000000", "d")),
            new KnownCharacteristic("TI SensorTag OAD Image Block",                     Guid.ParseExact("f000ffc2-0451-4000-b000-000000000000", "d")),

            new KnownCharacteristic("RedBearLabs Biscuit Read",                                     Guid.ParseExact("713d0001-503e-4c75-ba94-3148f18d941e", "d")),
            new KnownCharacteristic("RedBearLabs Biscuit TX_DATA_CHAR_UUID Notify",                 Guid.ParseExact("713d0002-503e-4c75-ba94-3148f18d941e", "d")),
            new KnownCharacteristic("RedBearLabs Biscuit RX_DATA_CHAR_UUID WriteWithoutResponse",   Guid.ParseExact("713d0003-503e-4c75-ba94-3148f18d941e", "d")),
            new KnownCharacteristic("RedBearLabs Biscuit BAUDRATE_CHAR_UUID WriteWithoutResponse",  Guid.ParseExact("713d0004-503e-4c75-ba94-3148f18d941e", "d")),
            new KnownCharacteristic("RedBearLabs Biscuit DEV_NAME_CHAR_UUID Read",                  Guid.ParseExact("713d0005-503e-4c75-ba94-3148f18d941e", "d")),
            new KnownCharacteristic("RedBearLabs Biscuit VERSION_CHAR_UUID unknown",                Guid.ParseExact("713d0006-503e-4c75-ba94-3148f18d941e", "d")),
            new KnownCharacteristic("RedBearLabs Biscuit TX_POWER_CHAR_UUID unknown",               Guid.ParseExact("713d0007-503e-4c75-ba94-3148f18d941e", "d")),
        ];
    }
}