using System;
using System.Collections.Generic;
using System.Linq;

namespace Plugin.BLE.Abstractions
{
    /// <summary>
    /// Provides a list of known characteristics. Source:
    /// https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/Assigned_Numbers/out/en/Assigned_Numbers.pdf#3.8.2.4
    /// </summary>
    public static class KnownCharacteristics
    {
        static KnownCharacteristics()
        {
            //ToDo do we need a lock here?
            LookupTable = Characteristics.ToDictionary(c => c.Id, c => c);
        }

        /// <summary>
        /// Look up a known characteristic via its Id.
        /// </summary>
        public static KnownCharacteristic Lookup(Guid id)
        {
            return LookupTable.ContainsKey(id) ? LookupTable[id] : new KnownCharacteristic("Unknown characteristic", Guid.Empty);
        }

        private static readonly Dictionary<Guid, KnownCharacteristic> LookupTable;

        /// <summary>
        /// The list of characteristics.
        /// </summary>
        private static readonly List<KnownCharacteristic> Characteristics =
        [
            new KnownCharacteristic(0x2a00, "Device Name"),
            new KnownCharacteristic(0x2a01, "Appearance"),
            new KnownCharacteristic(0x2a02, "Peripheral Privacy Flag"),
            new KnownCharacteristic(0x2a03, "Reconnection Address"),
            new KnownCharacteristic(0x2a04, "Peripheral Preferred Connection Parameters"),
            new KnownCharacteristic(0x2a05, "Service Changed"),
            new KnownCharacteristic(0x2a06, "Alert Level"),
            new KnownCharacteristic(0x2a07, "Tx Power Level"),
            new KnownCharacteristic(0x2a08, "Date Time"),
            new KnownCharacteristic(0x2a09, "Day of Week"),
            new KnownCharacteristic(0x2a0a, "Day Date Time"),
            new KnownCharacteristic(0x2a0b, "Exact Time 100"),
            new KnownCharacteristic(0x2a0c, "Exact Time 256"),
            new KnownCharacteristic(0x2a0d, "DST Offset"),
            new KnownCharacteristic(0x2a0e, "Time Zone"),
            new KnownCharacteristic(0x2a0f, "Local Time Information"),

            new KnownCharacteristic(0x2a10, "Secondary Time Zone"),
            new KnownCharacteristic(0x2a11, "Time with DST"),
            new KnownCharacteristic(0x2a12, "Time Accuracy"),
            new KnownCharacteristic(0x2a13, "Time Source"),
            new KnownCharacteristic(0x2a14, "Reference Time Information"),
            new KnownCharacteristic(0x2a15, "Time Broadcast"),
            new KnownCharacteristic(0x2a16, "Time Update Control Point"),
            new KnownCharacteristic(0x2a17, "Time Update State"),
            new KnownCharacteristic(0x2a18, "Glucose Measurement"),
            new KnownCharacteristic(0x2a19, "Battery Level"),
            new KnownCharacteristic(0x2a1a, "Battery Power State"),
            new KnownCharacteristic(0x2a1b, "Battery Level State"),
            new KnownCharacteristic(0x2a1c, "Temperature Measurement"),
            new KnownCharacteristic(0x2a1d, "Temperature Type"),
            new KnownCharacteristic(0x2a1e, "Intermediate Temperature"),
            new KnownCharacteristic(0x2a1f, "Temperature in Celsius"),

            new KnownCharacteristic(0x2a20, "Temperature in Fahrenheit"),
            new KnownCharacteristic(0x2a21, "Measurement Interval"),
            new KnownCharacteristic(0x2a22, "Boot Keyboard Input Report"),
            new KnownCharacteristic(0x2a23, "System ID"),
            new KnownCharacteristic(0x2a24, "Model Number String"),
            new KnownCharacteristic(0x2a25, "Serial Number String"),
            new KnownCharacteristic(0x2a26, "Firmware Revision String"),
            new KnownCharacteristic(0x2a27, "Hardware Revision String"),
            new KnownCharacteristic(0x2a28, "Software Revision String"),
            new KnownCharacteristic(0x2a29, "Manufacturer Name String"),
            new KnownCharacteristic(0x2a2a, "IEEE 11073-20601 Regulatory Certification Data List"),
            new KnownCharacteristic(0x2a2b, "Current Time"),
            new KnownCharacteristic(0x2a2c, "Magnetic Declination"),
            new KnownCharacteristic(0x2a2d, "Latitude"),
            new KnownCharacteristic(0x2a2e, "Longitude"),
            new KnownCharacteristic(0x2a2f, "Position 2D"),

            new KnownCharacteristic(0x2a30, "Position 3D"),
            new KnownCharacteristic(0x2a31, "Scan Refresh"),
            new KnownCharacteristic(0x2a32, "Boot Keyboard Output Report"),
            new KnownCharacteristic(0x2a33, "Boot Mouse Input Report"),
            new KnownCharacteristic(0x2a34, "Glucose Measure Context"),
            new KnownCharacteristic(0x2a35, "Blood Pressure Measurement"),
            new KnownCharacteristic(0x2a36, "Intermediate Cuff Pressure"),
            new KnownCharacteristic(0x2a37, "Heart Rate Measurement"),
            new KnownCharacteristic(0x2a38, "Body Sensor Location"),
            new KnownCharacteristic(0x2a39, "Heart Rate Control Point"),
            new KnownCharacteristic(0x2a3a, "Removable"),
            new KnownCharacteristic(0x2a3b, "Service Required"),
            new KnownCharacteristic(0x2a3c, "Scientific Temperature in Celsius"),
            new KnownCharacteristic(0x2a3d, "String"),
            new KnownCharacteristic(0x2a3e, "Network Availability"),
            new KnownCharacteristic(0x2a3f, "Alert Status"),

            new KnownCharacteristic(0x2a40, "Ringer Control Point"),
            new KnownCharacteristic(0x2a41, "Ringer Setting"),
            new KnownCharacteristic(0x2a42, "Alert Category ID Bit Mask"),
            new KnownCharacteristic(0x2a43, "Alert Category ID"),
            new KnownCharacteristic(0x2a44, "Alert Notification Control Point"),
            new KnownCharacteristic(0x2a45, "Unread Alert Status"),
            new KnownCharacteristic(0x2a46, "New Alert"),
            new KnownCharacteristic(0x2a47, "Supported New Alert Category"),
            new KnownCharacteristic(0x2a48, "Supported Unread Alert Category"),
            new KnownCharacteristic(0x2a49, "Blood Pressure Feature"),
            new KnownCharacteristic(0x2a4a, "HID Information"),
            new KnownCharacteristic(0x2a4b, "Report Map"),
            new KnownCharacteristic(0x2a4c, "HID Control Point"),
            new KnownCharacteristic(0x2a4d, "Report"),
            new KnownCharacteristic(0x2a4e, "Protocol Mode"),
            new KnownCharacteristic(0x2a4f, "Scan Interval Window"),

            new KnownCharacteristic(0x2a50, "PnP ID"),
            new KnownCharacteristic(0x2a51, "Glucose Feature"),
            new KnownCharacteristic(0x2a52, "Record Access Control Point"),
            new KnownCharacteristic(0x2a53, "RSC Measurement"),
            new KnownCharacteristic(0x2a54, "RSC Feature"),
            new KnownCharacteristic(0x2a55, "SC Control Point"),
            new KnownCharacteristic(0x2a56, "Digital Input"),
            new KnownCharacteristic(0x2a57, "Digital Output"),
            new KnownCharacteristic(0x2a58, "Analog Input"),
            new KnownCharacteristic(0x2a5a, "Aggregate Input"),
            new KnownCharacteristic(0x2a5b, "CSC Measurement"),
            new KnownCharacteristic(0x2a5c, "CSC Feature"),
            new KnownCharacteristic(0x2a5d, "Sensor Location"),
            new KnownCharacteristic(0x2a5e, "PLX Spot-Check Measurement"),
            new KnownCharacteristic(0x2a5f, "PLX Continuous Measurement"),

            new KnownCharacteristic(0x2a60, "PLX Features"),
            new KnownCharacteristic(0x2a62, "PLX Control Point"),
            new KnownCharacteristic(0x2a63, "Cycling Power Measurement"),
            new KnownCharacteristic(0x2a64, "Cycling Power Vector"),
            new KnownCharacteristic(0x2a65, "Cycling Power Feature"),
            new KnownCharacteristic(0x2a66, "Cycling Power Control Point"),
            new KnownCharacteristic(0x2a67, "Location And Speed"),
            new KnownCharacteristic(0x2a68, "Navigation"),
            new KnownCharacteristic(0x2a69, "Position Quality"),
            new KnownCharacteristic(0x2a6a, "LN Feature"),
            new KnownCharacteristic(0x2a6b, "LN Control Point"),
            new KnownCharacteristic(0x2a6c, "Elevation"),
            new KnownCharacteristic(0x2a6d, "Pressure"),
            new KnownCharacteristic(0x2a6e, "Temperature"),
            new KnownCharacteristic(0x2a6f, "Humidity"),

            new KnownCharacteristic(0x2a70, "True Wind Speed"),
            new KnownCharacteristic(0x2a71, "True Wind Direction"),
            new KnownCharacteristic(0x2a72, "Apparent Wind Speed"),
            new KnownCharacteristic(0x2a73, "Apparent Wind Direction"),
            new KnownCharacteristic(0x2a74, "Gust Factor"),
            new KnownCharacteristic(0x2a75, "Pollen Concentration"),
            new KnownCharacteristic(0x2a76, "UV Index"),
            new KnownCharacteristic(0x2a77, "Irradiance"),
            new KnownCharacteristic(0x2a78, "Rainfall"),
            new KnownCharacteristic(0x2a79, "Wind Chill"),
            new KnownCharacteristic(0x2a7a, "Heat Index"),
            new KnownCharacteristic(0x2a7b, "Dew Point"),
            new KnownCharacteristic(0x2a7c, "Trend"),
            new KnownCharacteristic(0x2a7d, "Descriptor Value Changed"),
            new KnownCharacteristic(0x2a7e, "Aerobic Heart Rate Lower Limit"),
            new KnownCharacteristic(0x2a7f, "Aerobic Threshold"),

            new KnownCharacteristic(0x2a80, "Age"),
            new KnownCharacteristic(0x2a81, "Anaerobic Heart Rate Lower Limit"),
            new KnownCharacteristic(0x2a82, "Anaerobic Heart Rate Upper Limit"),
            new KnownCharacteristic(0x2a83, "Anaerobic Threshold"),
            new KnownCharacteristic(0x2a84, "Aerobic Heart Rate Upper Limit"),
            new KnownCharacteristic(0x2a85, "Date of Birth"),
            new KnownCharacteristic(0x2a86, "Date of Threshold Assessment"),
            new KnownCharacteristic(0x2a87, "Email Address"),
            new KnownCharacteristic(0x2a88, "Fat Burn Heart Rate Lower Limit"),
            new KnownCharacteristic(0x2a89, "Fat Burn Heart Rate Upper Limit"),
            new KnownCharacteristic(0x2a8a, "First Name"),
            new KnownCharacteristic(0x2a8b, "Five Zone Heart Rate Limits"),
            new KnownCharacteristic(0x2a8c, "Gender"),
            new KnownCharacteristic(0x2a8d, "Heart Rate Max"),
            new KnownCharacteristic(0x2a8e, "Height"),
            new KnownCharacteristic(0x2a8f, "Hip Circumference"),

            new KnownCharacteristic(0x2a90, "Last Name"),
            new KnownCharacteristic(0x2a91, "Maximum Recommended Heart Rate"),
            new KnownCharacteristic(0x2a92, "Resting Heart Rate"),
            new KnownCharacteristic(0x2a93, "Sport Type for Aerobic and Anaerobic Thresholds"),
            new KnownCharacteristic(0x2a94, "Three Zone Heart Rate Limits"),
            new KnownCharacteristic(0x2a95, "Two Zone Heart Rate Limit"),
            new KnownCharacteristic(0x2a96, "VO2 Max"),
            new KnownCharacteristic(0x2a97, "Waist Circumference"),
            new KnownCharacteristic(0x2a98, "Weight"),
            new KnownCharacteristic(0x2a99, "Database Change Increment"),
            new KnownCharacteristic(0x2a9a, "User Index"),
            new KnownCharacteristic(0x2a9b, "Body Composition Feature"),
            new KnownCharacteristic(0x2a9c, "Body Composition Measurement"),
            new KnownCharacteristic(0x2a9d, "Weight Measurement"),
            new KnownCharacteristic(0x2a9e, "Weight Scale Feature"),
            new KnownCharacteristic(0x2a9f, "User Control Point"),

            new KnownCharacteristic(0x2aa0, "Magnetic Flux Density - 2D"),
            new KnownCharacteristic(0x2aa1, "Magnetic Flux Density - 3D"),
            new KnownCharacteristic(0x2aa2, "Language"),
            new KnownCharacteristic(0x2aa3, "Barometric Pressure Trend"),
            new KnownCharacteristic(0x2aa4, "Bond Management Control Point"),
            new KnownCharacteristic(0x2aa5, "Bond Management Feature"),
            new KnownCharacteristic(0x2aa6, "Central Address Resolution"),
            new KnownCharacteristic(0x2aa7, "CGM Measurement"),
            new KnownCharacteristic(0x2aa8, "CGM Feature"),
            new KnownCharacteristic(0x2aa9, "CGM Status"),
            new KnownCharacteristic(0x2aaa, "CGM Session Start Time"),
            new KnownCharacteristic(0x2aab, "CGM Session Run Time"),
            new KnownCharacteristic(0x2aac, "CGM Specific Ops Control Point"),
            new KnownCharacteristic(0x2aad, "Indoor Positioning Configuration"),
            new KnownCharacteristic(0x2aae, "Latitude"),
            new KnownCharacteristic(0x2aaf, "Longitude"),

            new KnownCharacteristic(0x2ab0, "Local North Coordinate"),
            new KnownCharacteristic(0x2ab1, "Local East Coordinate"),
            new KnownCharacteristic(0x2ab2, "Floor Number"),
            new KnownCharacteristic(0x2ab3, "Altitude"),
            new KnownCharacteristic(0x2ab4, "Uncertainty"),
            new KnownCharacteristic(0x2ab5, "Location Name"),
            new KnownCharacteristic(0x2ab6, "URI"),
            new KnownCharacteristic(0x2ab7, "HTTP Headers"),
            new KnownCharacteristic(0x2ab8, "HTTP Status Code"),
            new KnownCharacteristic(0x2ab9, "HTTP Entity Body"),
            new KnownCharacteristic(0x2aba, "HTTP Control Point"),
            new KnownCharacteristic(0x2abb, "HTTPS Security"),
            new KnownCharacteristic(0x2abc, "TDS Control Point"),
            new KnownCharacteristic(0x2abd, "OTS Feature"),
            new KnownCharacteristic(0x2abe, "Object Name"),
            new KnownCharacteristic(0x2abf, "Object Type"),
            
            new KnownCharacteristic(0x2ac0, "Object Size"),
            new KnownCharacteristic(0x2ac1, "Object First-Created"),
            new KnownCharacteristic(0x2ac2, "Object Last-Modified"),
            new KnownCharacteristic(0x2ac3, "Object ID"),
            new KnownCharacteristic(0x2ac4, "Object Properties"),
            new KnownCharacteristic(0x2ac5, "Object Action Control Point"),
            new KnownCharacteristic(0x2ac6, "Object List Control Point"),
            new KnownCharacteristic(0x2ac7, "Object List Filter"),
            new KnownCharacteristic(0x2ac8, "Object Changed"),
            new KnownCharacteristic(0x2ac9, "Resolvable Private Address Only"),
            new KnownCharacteristic(0x2acc, "Fitness Machine Feature"),
            new KnownCharacteristic(0x2acd, "Treadmill Data"),
            new KnownCharacteristic(0x2ace, "Cross Trainer Data"),
            new KnownCharacteristic(0x2acf, "Step Climber Data"),

            new KnownCharacteristic(0x2ad0, "Stair Climber Data"),
            new KnownCharacteristic(0x2ad1, "Rower Data"),
            new KnownCharacteristic(0x2ad2, "Indoor Bike Data"),
            new KnownCharacteristic(0x2ad3, "Training Status"),
            new KnownCharacteristic(0x2ad4, "Supported Speed Range"),
            new KnownCharacteristic(0x2ad5, "Supported Inclination Range"),
            new KnownCharacteristic(0x2ad6, "Supported Resistance Level Range"),
            new KnownCharacteristic(0x2ad7, "Supported Heart Rate Range"),
            new KnownCharacteristic(0x2ad8, "Supported Power Range"),
            new KnownCharacteristic(0x2ad9, "Fitness Machine Control Point"),
            new KnownCharacteristic(0x2ada, "Fitness Machine Status"),
            new KnownCharacteristic(0x2adb, "Mesh Provisioning Data In"),
            new KnownCharacteristic(0x2adc, "Mesh Provisioning Data Out"),
            new KnownCharacteristic(0x2add, "Mesh Proxy Data In"),
            new KnownCharacteristic(0x2ade, "Mesh Proxy Data Out"),
        
            new KnownCharacteristic("0000ffe1-0000-1000-8000-00805f9b34fb", "TI SensorTag Keys Data"),

            new KnownCharacteristic("f000aa01-0451-4000-b000-000000000000", "TI SensorTag Infrared Temperature Data"),
            new KnownCharacteristic("f000aa02-0451-4000-b000-000000000000", "TI SensorTag Infrared Temperature On/Off"),
            new KnownCharacteristic("f000aa03-0451-4000-b000-000000000000", "TI SensorTag Infrared Temperature Sample Rate"),
            new KnownCharacteristic("f000aa11-0451-4000-b000-000000000000", "TI SensorTag Accelerometer Data"),
            new KnownCharacteristic("f000aa12-0451-4000-b000-000000000000", "TI SensorTag Accelerometer On/Off"),
            new KnownCharacteristic("f000aa13-0451-4000-b000-000000000000", "TI SensorTag Accelerometer Sample Rate"),
            new KnownCharacteristic("f000aa21-0451-4000-b000-000000000000", "TI SensorTag Humidity Data"),
            new KnownCharacteristic("f000aa22-0451-4000-b000-000000000000", "TI SensorTag Humidity On/Off"),
            new KnownCharacteristic("f000aa23-0451-4000-b000-000000000000", "TI SensorTag Humidity Sample Rate"),
            new KnownCharacteristic("f000aa31-0451-4000-b000-000000000000", "TI SensorTag Magnometer Data"),
            new KnownCharacteristic("f000aa32-0451-4000-b000-000000000000", "TI SensorTag Magnometer On/Off"),
            new KnownCharacteristic("f000aa33-0451-4000-b000-000000000000", "TI SensorTag Magnometer Sample Rate"),
            new KnownCharacteristic("f000aa41-0451-4000-b000-000000000000", "TI SensorTag Barometer Data"),
            new KnownCharacteristic("f000aa42-0451-4000-b000-000000000000", "TI SensorTag Barometer On/Off"),
            new KnownCharacteristic("f000aa43-0451-4000-b000-000000000000", "TI SensorTag Barometer Calibration"),
            new KnownCharacteristic("f000aa44-0451-4000-b000-000000000000", "TI SensorTag Barometer Sample Rate"),
            new KnownCharacteristic("f000aa51-0451-4000-b000-000000000000", "TI SensorTag Gyroscope Data"),
            new KnownCharacteristic("f000aa52-0451-4000-b000-000000000000", "TI SensorTag Gyroscope On/Off"),
            new KnownCharacteristic("f000aa53-0451-4000-b000-000000000000", "TI SensorTag Gyroscope Sample Rate"),
            new KnownCharacteristic("f000aa61-0451-4000-b000-000000000000", "TI SensorTag Test Data"),
            new KnownCharacteristic("f000aa62-0451-4000-b000-000000000000", "TI SensorTag Test Configuration"),
            new KnownCharacteristic("f000ccc1-0451-4000-b000-000000000000", "TI SensorTag Connection Parameters"),
            new KnownCharacteristic("f000ccc2-0451-4000-b000-000000000000", "TI SensorTag Connection Request Parameters"),
            new KnownCharacteristic("f000ccc3-0451-4000-b000-000000000000", "TI SensorTag Connection Request Disconnect"),
            new KnownCharacteristic("f000ffc1-0451-4000-b000-000000000000", "TI SensorTag OAD Image Identify"),
            new KnownCharacteristic("f000ffc2-0451-4000-b000-000000000000", "TI SensorTag OAD Image Block"),

            new KnownCharacteristic("713d0001-503e-4c75-ba94-3148f18d941e", "RedBearLabs Biscuit Read"),
            new KnownCharacteristic("713d0002-503e-4c75-ba94-3148f18d941e", "RedBearLabs Biscuit TX_DATA_CHAR_UUID Notify"),
            new KnownCharacteristic("713d0003-503e-4c75-ba94-3148f18d941e", "RedBearLabs Biscuit RX_DATA_CHAR_UUID WriteWithoutResponse"),
            new KnownCharacteristic("713d0004-503e-4c75-ba94-3148f18d941e", "RedBearLabs Biscuit BAUDRATE_CHAR_UUID WriteWithoutResponse"),
            new KnownCharacteristic("713d0005-503e-4c75-ba94-3148f18d941e", "RedBearLabs Biscuit DEV_NAME_CHAR_UUID Read"),
            new KnownCharacteristic("713d0006-503e-4c75-ba94-3148f18d941e", "RedBearLabs Biscuit VERSION_CHAR_UUID unknown"),
            new KnownCharacteristic("713d0007-503e-4c75-ba94-3148f18d941e", "RedBearLabs Biscuit TX_POWER_CHAR_UUID unknown"),
        ];
    }
}