#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BLE.Client.Droid.Resource", IsApplication=true)]

namespace BLE.Client.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Plugins.BLE.Droid.Resource.Attribute.MvxBind = global::BLE.Client.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::BLE.Client.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Attribute.MvxGroupItemTemplate = global::BLE.Client.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Attribute.MvxItemTemplate = global::BLE.Client.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Attribute.MvxLang = global::BLE.Client.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Attribute.MvxSource = global::BLE.Client.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Attribute.MvxTemplate = global::BLE.Client.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Id.MvvmCrossTagId = global::BLE.Client.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Id.MvxBindingTagUnique = global::BLE.Client.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Plugins.BLE.Droid.Resource.String.ApplicationName = global::BLE.Client.Droid.Resource.String.ApplicationName;
			global::MvvmCross.Plugins.BLE.Droid.Resource.String.Hello = global::BLE.Client.Droid.Resource.String.Hello;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxBinding = global::BLE.Client.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxBinding_MvxBind = global::BLE.Client.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxBinding_MvxLang = global::BLE.Client.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxControl = global::BLE.Client.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::BLE.Client.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxExpandableListView = global::BLE.Client.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::BLE.Client.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxImageView = global::BLE.Client.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxImageView_MvxSource = global::BLE.Client.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxListView = global::BLE.Client.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::BLE.Client.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Plugins.BLE.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::BLE.Client.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
